# **ETL**
### (Extraction, Transformation & Loading)

### Change Working Directory ###

- Access current directory

In [1]:
import os
current_dir = os.getcwd()
current_dir

'c:\\Users\\mikee\\Desktop\\NHSProject\\NoteBooks'

- Make the parent of the current directory the new current directory
    * os.path.dirname() gets the parent directory
    * os.chir() defines the new current directory

In [2]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

- Confirm the directory

In [3]:
current_dir = os.getcwd()
current_dir

'c:\\Users\\mikee\\Desktop\\NHSProject'

## ETRACTION ##

Import Libraries

In [4]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

In [5]:
#reading in the data
df = pd.read_csv("Data/jobs_raw.csv")
df.head().transpose()

,0,1,2,3,4
job_title,Trainee Advanced Clinical Practitioner,Trust Doctor in Obstetrics & Gynaecology,Fixed Term Consultant Urological Surgeon,Research Fellow in Psychiatry,Clinical Teaching Fellow in Ophthalmology
job_reference,J180-A-19-286627,259-TG-APROT-A-RLHO&G,179-MSC08-19,263-MED19-007,259-MED1643381WXH
employer,Central Advertising - General Practitioners,Barts Health NHS Trust,West Suffolk NHS Foundation Trust,Northumberland Tyne and Wear NHS Foundation Trust,Barts Health NHS Trust
employer_postcode,CF37 1LB,E1 8PR,IP33 2QZ,NE3 3XT,E1 8PR
department,Trinity Medical Centre,Obstetrics & Gynaecology,Urology,Psychiatry,Medical and Dental
location,Wakefield,"Obs & Gynae Medical Staff - RLH, London",Bury St. Edmunds,"St Nicholas Hospital, Gosforth","Whipps Cross Hospital, London"
salary,TBC,"£31,217 to £49,086 pa","£77,913 to £105,042 pa","£31,217 to £49,086","£31,217 - £49,086 per annum"
job_type,Fixed term (2 years),Fixed term (6 months),Fixed term (12 months),Fixed term (6-12 Months),Fixed term
working_pattern,TBC,40,11 Sessions/Week,Full Time 40 hours per week,32 hours per week
pay_scheme,Other,Hospital Medical and Dental Staff,Hospital Medical and Dental Staff,Hospital Medical and Dental Staff,Other
pay_band,NaN,Doctor - Other,Consultant,Doctor - Other,NaN
staff_group,Medical & Dental,Medical & Dental,Medical & Dental,Medical & Dental,Medical & Dental
specialty,NaN,Obstetrics & Gynaecology,Urology,Psychiatry,Medical and Dental
full_description,Trinity Medical Centre are currently seeking a...,This Trust post is a Fixed Term Part Time Clin...,An opportunity has arisen for a Fixed Term Con...,Would you like to work in a CQC ‘Outstanding’ ...,Clinical Teaching Fellow in Ophthalmology 12 m...
json_salary_max,NaN,49086.0,105042.0,49086.0,49086.0
json_salary_min,NaN,31217.0,77913.0,31217.0,31217.0
json_salary_unit,NaN,YEAR,YEAR,YEAR,YEAR
json_salary_value,TBC,"£31,217 to £49,086 pa","£77,913 to £105,042 pa","£31,217 to £49,086","£31,217 - £49,086 per annum"
json_date_posted,2019-03-26T15:42:20+0000,2019-03-25T18:15:16+0000,2019-03-25T12:45:10+0000,2019-03-25T13:45:57+0000,2019-03-25T18:15:19+0000
json_description,&lt;p&gt;Trinity Medical Centre are currently ...,&lt;p&gt;&lt;strong&gt;This Trust post is a Fi...,&lt;p&gt;&lt;span&gt;An opportunity has arisen...,&lt;p&gt;Would you like to work in a CQC ‘Outs...,&lt;p&gt;&lt;strong&gt;Clinical Teaching Fello...
json_employment_type,FULL_TIME,FULL_TIME,FULL_TIME,FULL_TIME,FULL_TIME
json_hire_name,Central Advertising - General Practitioners,Barts Health NHS Trust,West Suffolk NHS Foundation Trust,Northumberland Tyne and Wear NHS Foundation Trust,Barts Health NHS Trust
json_address_locality,Wakefield,"Obs &amp; Gynae Medical Staff - RLH, London",Bury St. Edmunds,"St Nicholas Hospital, Gosforth","Whipps Cross Hospital, London"
json_address_postcode,WF1 1PG,E1 1BB,IP33 2QZ,NE3 3XT,E11 1NR
json_lat,53.68,51.519,52.2317,55.0063,51.5788
json_lng,-1.49482,-0.058048,0.709205,-1.63477,0.002666
json_title,Trainee Advanced Clinical Practitioner,Trust Doctor in Obstetrics &amp; Gynaecology,Fixed Term Consultant Urological Surgeon,Research Fellow in Psychiatry,Clinical Teaching Fellow in Ophthalmology
json_closing_date,09/04/2019 23:59,14/04/2019 23:59,09/04/2019 23:59,22/04/2019 23:59,22/04/2019 23:59
scrape_dt,27/03/2019 13:32,27/03/2019 13:32,27/03/2019 13:32,27/03/2019 13:32,27/03/2019 13:32

In [6]:
#Check df information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27482 entries, 0 to 27481
Data columns (total 29 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title              27482 non-null  object
 1   job_reference          27482 non-null  object
 2   employer               27482 non-null  object
 3   employer_postcode      27482 non-null  object
 4   department             23851 non-null  object
 5   location               27482 non-null  object
 6   salary                 27478 non-null  object
 7   job_type               27482 non-null  object
 8   working_pattern        23040 non-null  object
 9   pay_scheme             27482 non-null  object
 10  pay_band               15840 non-null  object
 11  staff_group            27482 non-null  object
 12  specialty              22554 non-null  object
 13  full_description       27482 non-null  object
 14  json_salary_max        23455 non-null  float64
 15  json_salary_min        23455 non-null  float64
 16  json_salary_unit       23455 non-null  object
 17  json_salary_value      27478 non-null  object
 18  json_date_posted       27482 non-null  object
 19  json_description       27482 non-null  object
 20  json_employment_type   27482 non-null  object
 21  json_hire_name         27482 non-null  object
 22  json_address_locality  27482 non-null  object
 23  json_address_postcode  27482 non-null  object
 24  json_lat               27482 non-null  float64
 25  json_lng               27482 non-null  float64
 26  json_title             27482 non-null  object
 27  json_closing_date      27482 non-null  object
 28  scrape_dt              27482 non-null  object
dtypes: float64(4), object(25)
memory usage: 6.1+ MB

### Check For Missing Values & Other Anomalies ###

In [7]:
df.isnull().sum()

job_title                    0
job_reference                0
employer                     0
employer_postcode            0
department                3631
location                     0
salary                       4
job_type                     0
working_pattern           4442
pay_scheme                   0
pay_band                 11642
staff_group                  0
specialty                 4928
full_description             0
json_salary_max           4027
json_salary_min           4027
json_salary_unit          4027
json_salary_value            4
json_date_posted             0
json_description             0
json_employment_type         0
json_hire_name               0
json_address_locality        0
json_address_postcode        0
json_lat                     0
json_lng                     0
json_title                   0
json_closing_date            0
scrape_dt                    0
dtype: int64

### TRANSORMATION ###

Given pay_band is missing for almost half of all values it is best to drop that column. For now I will also drop the columns json_salary_max, json_salary_min, json_salary_unit. 
I will keep spciality for now as it may be possible to infer from salary etc

In [8]:
df = df.drop(columns=['pay_band','json_salary_max','json_salary_min','json_salary_unit'])
df.shape
df.head().transpose()

,0,1,2,3,4
job_title,Trainee Advanced Clinical Practitioner,Trust Doctor in Obstetrics & Gynaecology,Fixed Term Consultant Urological Surgeon,Research Fellow in Psychiatry,Clinical Teaching Fellow in Ophthalmology
job_reference,J180-A-19-286627,259-TG-APROT-A-RLHO&G,179-MSC08-19,263-MED19-007,259-MED1643381WXH
employer,Central Advertising - General Practitioners,Barts Health NHS Trust,West Suffolk NHS Foundation Trust,Northumberland Tyne and Wear NHS Foundation Trust,Barts Health NHS Trust
employer_postcode,CF37 1LB,E1 8PR,IP33 2QZ,NE3 3XT,E1 8PR
department,Trinity Medical Centre,Obstetrics & Gynaecology,Urology,Psychiatry,Medical and Dental
location,Wakefield,"Obs & Gynae Medical Staff - RLH, London",Bury St. Edmunds,"St Nicholas Hospital, Gosforth","Whipps Cross Hospital, London"
salary,TBC,"£31,217 to £49,086 pa","£77,913 to £105,042 pa","£31,217 to £49,086","£31,217 - £49,086 per annum"
job_type,Fixed term (2 years),Fixed term (6 months),Fixed term (12 months),Fixed term (6-12 Months),Fixed term
working_pattern,TBC,40,11 Sessions/Week,Full Time 40 hours per week,32 hours per week
pay_scheme,Other,Hospital Medical and Dental Staff,Hospital Medical and Dental Staff,Hospital Medical and Dental Staff,Other
staff_group,Medical & Dental,Medical & Dental,Medical & Dental,Medical & Dental,Medical & Dental
specialty,NaN,Obstetrics & Gynaecology,Urology,Psychiatry,Medical and Dental
full_description,Trinity Medical Centre are currently seeking a...,This Trust post is a Fixed Term Part Time Clin...,An opportunity has arisen for a Fixed Term Con...,Would you like to work in a CQC ‘Outstanding’ ...,Clinical Teaching Fellow in Ophthalmology 12 m...
json_salary_value,TBC,"£31,217 to £49,086 pa","£77,913 to £105,042 pa","£31,217 to £49,086","£31,217 - £49,086 per annum"
json_date_posted,2019-03-26T15:42:20+0000,2019-03-25T18:15:16+0000,2019-03-25T12:45:10+0000,2019-03-25T13:45:57+0000,2019-03-25T18:15:19+0000
json_description,&lt;p&gt;Trinity Medical Centre are currently ...,&lt;p&gt;&lt;strong&gt;This Trust post is a Fi...,&lt;p&gt;&lt;span&gt;An opportunity has arisen...,&lt;p&gt;Would you like to work in a CQC ‘Outs...,&lt;p&gt;&lt;strong&gt;Clinical Teaching Fello...
json_employment_type,FULL_TIME,FULL_TIME,FULL_TIME,FULL_TIME,FULL_TIME
json_hire_name,Central Advertising - General Practitioners,Barts Health NHS Trust,West Suffolk NHS Foundation Trust,Northumberland Tyne and Wear NHS Foundation Trust,Barts Health NHS Trust
json_address_locality,Wakefield,"Obs &amp; Gynae Medical Staff - RLH, London",Bury St. Edmunds,"St Nicholas Hospital, Gosforth","Whipps Cross Hospital, London"
json_address_postcode,WF1 1PG,E1 1BB,IP33 2QZ,NE3 3XT,E11 1NR
json_lat,53.68,51.519,52.2317,55.0063,51.5788
json_lng,-1.49482,-0.058048,0.709205,-1.63477,0.002666
json_title,Trainee Advanced Clinical Practitioner,Trust Doctor in Obstetrics &amp; Gynaecology,Fixed Term Consultant Urological Surgeon,Research Fellow in Psychiatry,Clinical Teaching Fellow in Ophthalmology
json_closing_date,09/04/2019 23:59,14/04/2019 23:59,09/04/2019 23:59,22/04/2019 23:59,22/04/2019 23:59
scrape_dt,27/03/2019 13:32,27/03/2019 13:32,27/03/2019 13:32,27/03/2019 13:32,27/03/2019 13:32

In [9]:
#check for unique values per column
df.nunique()

job_title                11477
job_reference            23683
employer                   487
employer_postcode          420
department                4508
location                  5392
salary                    5420
job_type                   930
working_pattern           2874
pay_scheme                   4
staff_group                  1
specialty                 3326
full_description         22789
json_salary_value         5419
json_date_posted         26339
json_description         23147
json_employment_type         5
json_hire_name             487
json_address_locality     5384
json_address_postcode     3214
json_lat                  2989
json_lng                  3180
json_title               11427
json_closing_date          311
scrape_dt                 3072
dtype: int64

In [10]:
#check for duplicates
df[df.duplicated()]

,job_title,job_reference,employer,employer_postcode,department,location,salary,job_type,working_pattern,pay_scheme,...,json_description,json_employment_type,json_hire_name,json_address_locality,json_address_postcode,json_lat,json_lng,json_title,json_closing_date,scrape_dt
8504,General Practitioners - Ealing UCC,J257-A-18-0769,Greenbrook Healthcare,UB3 4AZ,Ealing Urgent Care Centre,Ealing,Competitive,Permanent,NaN,Other,...,"&lt;p&gt;Lead by a team of excellent GPs, Emer...",FULL_TIME,Greenbrook Healthcare,Ealing,UB1 3HW,51.5070,-0.346317,General Practitioners - Ealing UCC,31/07/2019 23:59,24/05/2019 02:40
8507,Locum Consultant Clinical Oncologist,261-52-18CICLM,North Cumbria University Hospitals NHS Trust,CA2 7HY,Radiotherapy,Carlisle,"£77,913 - £105,042 pa",Locum (12 months),40 Hours/Week,Hospital Medical and Dental Staff,...,&lt;p&gt;North Cumbria University Hospitals NH...,FULL_TIME,North Cumbria University Hospitals NHS Trust,Carlisle,CA2 7HY,54.8958,-2.955300,Locum Consultant Clinical Oncologist,20/06/2019 23:59,24/05/2019 01:36
8508,Trust Doctor in Haematology,293-IMRS-MED-0059-A,Homerton University Hospital NHS Trust,E9 6SR,Haematology,"Homerton University Hospital, London","£31,217-£49,086 per annum pro rata",Fixed term,40,Hospital Medical and Dental Staff,...,&lt;p&gt;Homerton University Hospital NHS Foun...,FULL_TIME,Homerton University Hospital NHS Trust,"Homerton University Hospital, London",E9 6SR,51.5506,-0.046072,Trust Doctor in Haematology,05/06/2019 23:59,24/05/2019 01:36
8509,Band 6 Physiotherapist (Civilian),J221-A-19-11434,Ministry of Defence (Defence Medical Services),WS14 9PY,Queen Elizabeth Memorial Health Centre,Tidworth,"£30,401-£37,267 per annum (pro-rata if part time)",Permanent,Full Time/Part Time/Job Share,Agenda for change,...,&lt;p&gt;Are you a highly skilled Physiotherap...,FULL_TIME,Ministry of Defence (Defence Medical Services),Tidworth,SP9 7EA,51.2340,-1.670150,Band 6 Physiotherapist (Civilian),09/06/2019 23:59,24/05/2019 01:36
8510,Locum Consultant in Anaesthetics,435-MQ95-19,East Lancashire Hospitals NHS Trust,BB10 2PQ,Consultant,East Lancashire,"£77,913 to £105,042 pa",Fixed term (6 months),10 PA''s,Hospital Medical and Dental Staff,...,&lt;p&gt;Locum Consultant in Anaesthetics&lt;/...,FULL_TIME,East Lancashire Hospitals NHS Trust,East Lancashire,BB2 3HH,53.7366,-2.466800,Locum Consultant in Anaesthetics,19/06/2019 23:59,24/05/2019 01:36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8932,Junior Specialist Doctor (Higher) in Obstetric...,381-A-19-98472,Sandwell and West Birmingham Hospitals NHS Trust,B18 7QH,Obstetrics and Gynaecology,Birmingham and West Browmich,"MT04 (£47,132)",Fixed term,Full shift,Hospital Medical and Dental Staff,...,&lt;p&gt;&lt;strong&gt;&lt;span style=&quot;te...,FULL_TIME,Sandwell and West Birmingham Hospitals NHS Trust,Birmingham and West Browmich,B18 7QH,52.4898,-1.929420,Junior Specialist Doctor (Higher) in Obstetric...,03/06/2019 23:59,24/05/2019 02:41
8933,Clinical Research Fellowship in Gastroenterology,200-MCCBEG-1680251-BK,St George''s University Hospitals NHS Foundati...,SW17 0QT,Gastroenterology,"St George''s Hospital, London","£31,217 - £49,086",Fixed term,20,Hospital Medical and Dental Staff,...,&lt;p&gt;The research fellow will take up 0.5 ...,FULL_TIME,St George''s University Hospitals NHS Foundati...,"St George&#39;s Hospital, London",SW17 0QT,51.4267,-0.175721,Clinical Research Fellowship in Gastroenterology,31/05/2019 23:59,24/05/2019 02:41
8934,Perioperative Practitioner - 37.5 Hours,L24-MER-POP-30,British Pregnancy Advisory Service (bpas),CV37 9BF,BPAS Merseyside,Merseyside,"£24,307-£29,365 per annum pro rata",Permanent,37.5 hours per week,Other,...,&lt;p&gt;&lt;strong&gt;Are you a Registered Nu...,FULL_TIME,British Pregnancy Advisory Service (bpas),Merseyside,L17 8UJ,53.3817,-2.949790,Perioperative Practitioner - 37.5 Hours,03/06/2019 23:59,24/05/2019 02:41
8936,Locum Consultant,298-MED-2320,Emergency & Specialty Medicine,LS9 7TF,298 Medical Staff - Infectious Diseases SJH,St James University Hospital,"£77,913 to £105,042 pa",Locum (Six months),10 PAs,Hospital Medical and Dental Staff,...,&lt;p&gt;&lt;strong&gt;&lt;span style=&quot;te...,FULL_TIME,Emergency & Specialty Medicine,St James University Hospital,LS9 7TF,53.8073,-1.519080,Locum Consultant,03/06/2019 23:59,24/05/2019 02:41
8937,Lead Consultant Rheumatologist,426-163-19KA-A,The Queen Elizabeth Hospital King''s Lynn NHS ...,PE30 4ET,Rheumatology,"King''s Lynn, King''s Lynn","£77,,913 - £105,042",Permanent,Full time,Hospital Medical and Dental Staff,...,&lt;p&gt;Great care can change everything and ...,FULL_TIME,The Queen Elizabeth Hospital King''s Lynn NHS ...,"King&#39;s Lynn, King&#39;s Lynn",PE30 4ET,52.7568,0.447015,Lead Consultant Rheumatologist,17/06/2019 23:59,24/05/2019 02:41

In [11]:
#Drop duplicates
df = df.drop_duplicates()
df.shape

(27384, 25)

## LOAD ##

Load the df into a csv file for further processing in CCMS

In [12]:
# Save the cleaned data as a compressed CSV for GitHub-friendly storage
# Git can track .csv.gz files, and pandas can read them back directly.
df.to_csv("Data/jobs_cleaned.csv.gz", index=False, compression="gzip")

In [13]:
# Save the cleaned data as a CSV for local use
df.to_csv("Data/jobs_cleaned.csv", index=False)

In [ ]:
from pathlib import Path
import zipfile


def clean_text(series):
    return series.fillna("").astype(str).str.strip()


output_dir = Path("Data/schema_tables")
output_dir.mkdir(parents=True, exist_ok=True)

raw_df = pd.read_csv("Data/jobs_raw.csv")

organisations = pd.DataFrame({
    "organisation_name": clean_text(raw_df["employer"])
})
organisations = organisations[organisations["organisation_name"] != ""].drop_duplicates().reset_index(drop=True)
organisations.insert(0, "organisation_id", range(1, len(organisations) + 1))
organisations["organisation_type"] = ""
organisations["website"] = ""
organisations = organisations[["organisation_id", "organisation_name", "organisation_type", "website"]]
org_lookup = dict(zip(organisations["organisation_name"], organisations["organisation_id"]))


department_source = pd.DataFrame({
    "organisation_name": clean_text(raw_df["employer"]),
    "department_name": clean_text(raw_df["department"]),
})
department_source = department_source[
    (department_source["organisation_name"] != "") & (department_source["department_name"] != "")
].drop_duplicates().reset_index(drop=True)
department_source["organisation_id"] = department_source["organisation_name"].map(org_lookup)
department_source.insert(0, "department_id", range(1, len(department_source) + 1))
department_source = department_source[["department_id", "organisation_id", "department_name"]]


location_source = pd.DataFrame({
    "site_name": clean_text(raw_df["location"]),
    "city": clean_text(raw_df["json_address_locality"]),
    "county": "",
    "postcode": clean_text(raw_df["json_address_postcode"]).replace("", pd.NA).fillna(clean_text(raw_df["employer_postcode"])),
    "region": "",
    "country": "",
})
location_source = location_source[location_source["site_name"] != ""].drop_duplicates().reset_index(drop=True)
location_source.insert(0, "location_id", range(1, len(location_source) + 1))
location_source = location_source[["location_id", "site_name", "city", "county", "postcode", "region", "country"]]


occupation_source = pd.DataFrame({
    "category": clean_text(raw_df["staff_group"]),
    "specialty": clean_text(raw_df["specialty"]),
    "nhs_band": clean_text(raw_df["pay_band"]),
})
occupation_source = occupation_source[
    (occupation_source["category"] != "")
    | (occupation_source["specialty"] != "")
    | (occupation_source["nhs_band"] != "")
].drop_duplicates().reset_index(drop=True)
occupation_source.insert(0, "occupation_id", range(1, len(occupation_source) + 1))
occupation_source = occupation_source[["occupation_id", "category", "specialty", "nhs_band"]]


salary_source = pd.DataFrame({
    "minimum_salary": pd.to_numeric(raw_df["json_salary_min"], errors="coerce"),
    "maximum_salary": pd.to_numeric(raw_df["json_salary_max"], errors="coerce"),
    "salary_type": clean_text(raw_df["json_salary_unit"]),
    "pay_band": clean_text(raw_df["pay_band"]),
})
salary_source = salary_source.drop_duplicates().reset_index(drop=True)
salary_source.insert(0, "salary_id", range(1, len(salary_source) + 1))
salary_source = salary_source[["salary_id", "minimum_salary", "maximum_salary", "salary_type", "pay_band"]]


recruiter_source = pd.DataFrame({
    "name": clean_text(raw_df["json_hire_name"]),
})
recruiter_source = recruiter_source[recruiter_source["name"] != ""].drop_duplicates().reset_index(drop=True)
recruiter_source.insert(0, "recruiter_id", range(1, len(recruiter_source) + 1))
recruiter_source["email"] = ""
recruiter_source["phone"] = ""
recruiter_source = recruiter_source[["recruiter_id", "name", "email", "phone"]]
recruiter_lookup = dict(zip(recruiter_source["name"], recruiter_source["recruiter_id"]))


salary_lookup = {
    (row.minimum_salary, row.maximum_salary, row.salary_type, row.pay_band): row.salary_id
    for row in salary_source.itertuples(index=False)
}
occupation_lookup = {
    (row.category, row.specialty, row.nhs_band): row.occupation_id
    for row in occupation_source.itertuples(index=False)
}
location_lookup = {
    (row.site_name, row.city, row.postcode): row.location_id
    for row in location_source.itertuples(index=False)
}
department_lookup = {
    (row.organisation_id, row.department_name): row.department_id
    for row in department_source.itertuples(index=False)
}


job_source = pd.DataFrame({
    "reference_number": clean_text(raw_df["job_reference"]),
    "job_title": clean_text(raw_df["job_title"]),
    "job_description": clean_text(raw_df["full_description"]),
    "contract_type": clean_text(raw_df["job_type"]),
    "working_pattern": clean_text(raw_df["working_pattern"]),
    "employment_type": clean_text(raw_df["json_employment_type"]),
    "organisation_name": clean_text(raw_df["employer"]),
    "department_name": clean_text(raw_df["department"]),
    "site_name": clean_text(raw_df["location"]),
    "city": clean_text(raw_df["json_address_locality"]),
    "postcode": clean_text(raw_df["json_address_postcode"]).replace("", pd.NA).fillna(clean_text(raw_df["employer_postcode"])),
    "category": clean_text(raw_df["staff_group"]),
    "specialty": clean_text(raw_df["specialty"]),
    "nhs_band": clean_text(raw_df["pay_band"]),
    "salary_min": pd.to_numeric(raw_df["json_salary_min"], errors="coerce"),
    "salary_max": pd.to_numeric(raw_df["json_salary_max"], errors="coerce"),
    "salary_type": clean_text(raw_df["json_salary_unit"]),
    "recruiter_name": clean_text(raw_df["json_hire_name"]),
})
job_source = job_source[job_source["reference_number"] != ""].drop_duplicates(subset=["reference_number"]).reset_index(drop=True)
job_source.insert(0, "job_id", range(1, len(job_source) + 1))
job_source["organisation_id"] = job_source["organisation_name"].map(org_lookup)
job_source["department_id"] = [
    department_lookup.get((org_id, dept_name))
    for org_id, dept_name in zip(job_source["organisation_id"], job_source["department_name"])
]
job_source["location_id"] = [
    location_lookup.get((site, city, postcode))
    for site, city, postcode in zip(job_source["site_name"], job_source["city"], job_source["postcode"])
]
job_source["occupation_id"] = [
    occupation_lookup.get((category, specialty, band))
    for category, specialty, band in zip(job_source["category"], job_source["specialty"], job_source["nhs_band"])
]
job_source["salary_id"] = [
    salary_lookup.get((salary_min, salary_max, salary_type, pay_band))
    for salary_min, salary_max, salary_type, pay_band in zip(
        job_source["salary_min"], job_source["salary_max"], job_source["salary_type"], job_source["nhs_band"]
    )
]

job_table = job_source[[
    "job_id",
    "reference_number",
    "job_title",
    "job_description",
    "contract_type",
    "working_pattern",
    "employment_type",
    "organisation_id",
    "department_id",
    "location_id",
    "occupation_id",
    "salary_id",
]].copy()
job_table["status"] = ""
job_table = job_table[[
    "job_id",
    "reference_number",
    "job_title",
    "job_description",
    "contract_type",
    "working_pattern",
    "employment_type",
    "status",
    "organisation_id",
    "department_id",
    "location_id",
    "occupation_id",
    "salary_id",
]]

job_contact = pd.DataFrame({
    "job_id": job_source["job_id"],
    "recruiter_id": job_source["recruiter_name"].map(recruiter_lookup),
    "contact_type": "hiring_contact",
})

applicant = pd.DataFrame(columns=["applicant_id", "first_name", "last_name", "email"])
application = pd.DataFrame(columns=["application_id", "applicant_id", "job_id", "application_date", "status", "score"])

tables = {
    "organisation": organisations,
    "department": department_source,
    "location": location_source,
    "occupation": occupation_source,
    "salary": salary_source,
    "recruiter": recruiter_source,
    "job": job_table,
    "job_contact": job_contact,
    "applicant": applicant,
    "application": application,
}

written_files = []
for table_name, table_df in tables.items():
    csv_path = output_dir / f"{table_name}.csv"
    table_df.to_csv(csv_path, index=False)
    written_files.append(csv_path)

zip_path = Path("Data/schema_tables.zip")
with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
    for csv_path in written_files:
        archive.write(csv_path, arcname=csv_path.name)

print(f"Wrote {len(written_files)} table CSVs to {output_dir}")
print(f"Created archive: {zip_path}")